experiment_name: "DEBUG-TENSORBOARD"

data:
    train: "./data/ptb.train.txt"
    valid: "./data/ptb.valid.txt"
    test: "./data/ptb.test.txt"
    vocab: "./data/ptb.vocab.txt"

model:
    dim: 16
    beam_width: 2
    encoder:
        embedding_size: 300
        hidden_size: 256
        bidirectional: False
        # h_dim: 66 # should be dim * (dim - 1) / 2 if map_type is 'linear'
    normalizing_flow:
        map_type: 'planar'
        K: 16
    generator:
        embedding_size: 300
        hidden_size: 256

training:
    epochs: 50
    batch_size: 32
    learning_rate: 0.0003
    log_frequency: 100
    beta_0: -10.0
    beta_growth_rate: 0.002
    beta_trick_thr: 4
    max_length: 50
    ckpt_dir: "./data/ckpt"
    summary_dir: "./data/summary"
    word_dropout_rate: 0.75

