experiment_name: "ptb-linear"

data:
    train: "./data/ptb.train.txt"
    valid: "./data/ptb.valid.txt"
    test: "./data/ptb.test.txt"
    vocab: "./data/ptb.vocab.txt"

model:
    dim: 11
    encoder:
        embedding_size: 350
        hidden_size: 200
        bidirectional: False
        h_dim: 66 # should be dim * (dim - 1) / 2 if map_type is 'linear'
    normalizing_flow:
        map_type: 'linear'
        K: 1
    generator:
        embedding_size: 350
        hidden_size: 200

training:
    epochs: 30
    warmup_epochs: 3
    batch_size: 32
    learning_rate: 0.0005
    log_frequency: 100
    max_length: 50
    unk_weight: 1.0
    ckpt_dir: "./data/ckpt"
    summary_dir: "./data/summary"
    word_dropout_rate: 0.50

